version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
   
    steps:
      - checkout

      - run: mkdir dn-tools

      - run: dotnet tool install -g dotnet-sonarscanner

      - run: echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV

      - run: dotnet sonarscanner begin "/k:ProjectKey" "/n:ProjectName" "/d:sonar.host.url=https://sonarcloud.io" "/d:sonar.login=a4d55ec7e11d17e0e2a60205253c802be07739b9"

      - run: dotnet build

      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - run: dotnet sonarscanner end "/d:sonar.login=a4d55ec7e11d17e0e2a60205253c802be07739b9"

